###valid
PATCH http://localhost:8080/UpdateUser/21
Content-Type: application/json

{
  "Phone_num": "79123213212",
  "Mobile_code": "7",
  "Tag": "cool",
  "Timezone_abbrev" : "MSK"
}
###valid
POST http://localhost:8080/GetMailingListID/Beeline
Content-Type: application/json

{}
###valid
POST http://localhost:8080/AddUser
Content-Type: application/json

{
  "Phone_num": "73333333333",
  "Mobile_code": "43",
  "Tag": "cool",
  "Timezone_abbrev" : "MSK"
}
###not valid number
POST http://localhost:8080/AddUser
Content-Type: application/json

{
  "Phone_num": "aasd79164sass877712",
  "Mobile_code": "7",
  "Tag": "cool",
  "Timezone_abbrev" : "MSK"
}
###not tz
POST http://localhost:8080/AddUser
Content-Type: application/json

{
  "Phone_num": "79164877812",
  "Mobile_code": "7",
  "Tag": "cool",
  "Timezone_abbrev" : "NNASDN"
}
###GET
GET http://localhost:8080/GeneralStats
Content-Type: application/json

{
}

###GET
GET http://localhost:8080/GetUserID/79154877712
Content-Type: application/json

{
}

###GET
GET http://localhost:8080/GetMailingListID/Beeline
Content-Type: application/json

{
}

### GET
GET http://localhost:8080/DetailedStats/35
Content-Type: application/json

{
}
###03 Mar 17 12:00 MSK
POST http://localhost:8080/AddMailingList
Content-Type: application/json

{
  "Launch_date": "03 Mar 22 12:00 MSK",
  "Message" : "asdaszxccasdsazxczxcaadsasdasdsdsadsadasdasdasdasd!",
  "Filter" : "cool;43",
  "Finish_date" : "22 Mar 22 12:00 MSK"
}

###03 Mar 17 12:00 MSK
POST http://localhost:8080/AddMailingList
Content-Type: application/json

{
  "Launch_date": "03 Mar 17 12:00 MSK",
  "Message" : "Hello ssassadasdasdasddasd!",
  "Filter" : "fun;7",
  "Finish_date" : "22 Mar 22 12:00 MSK"

}

###03 Mar 17 12:00 MSK
POST http://localhost:8080/AddMailingList
Content-Type: application/json

{
  "Launch_date": "03 Mar 17 12:00 MSK",
  "Message" : "ssasdasdasdasdasdasdfgddasdasdasasdsasdasdasdasdasdasdasdasdasdsadasdaasdasdsssdasdsasd",
  "Filter" : "nice;7",
  "Finish_date" : "22 Mar 22 12:00 MSK"
}

###03 Mar 17 12:00 MSK
POST https://probe.fbrq.cloud/v1/send/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkwNjMwNjgsImlzcyI6ImZhYnJpcXVlIiwibmFtZSI6IkVnb3IifQ.Ns0At0MuQyUqNpeZk5qbxdhjzKC5QQ_NVLnhoqvQxc0

{
  "Id": 1,
  "Phone": 76666666666,
  "text": "ASDASDASDASDASDASDasdasdsad"
}

###DELETE
DELETE http://localhost:8080/DeleteMailingList/6
Content-Type: application/json

{}

